ALTER TABLE awm_receipts ADD COLUMN IF NOT EXISTS actor_harness TEXT NOT NULL DEFAULT '';
ALTER TABLE awm_receipts ADD COLUMN IF NOT EXISTS actor_model TEXT NOT NULL DEFAULT '';
ALTER TABLE awm_receipts ADD COLUMN IF NOT EXISTS actor_session TEXT NOT NULL DEFAULT '';

ALTER TABLE awm_runs ADD COLUMN IF NOT EXISTS actor_harness TEXT NOT NULL DEFAULT '';
ALTER TABLE awm_runs ADD COLUMN IF NOT EXISTS actor_model TEXT NOT NULL DEFAULT '';
ALTER TABLE awm_runs ADD COLUMN IF NOT EXISTS actor_session TEXT NOT NULL DEFAULT '';

ALTER TABLE awm_verification_batches ADD COLUMN IF NOT EXISTS actor_harness TEXT NOT NULL DEFAULT '';
ALTER TABLE awm_verification_batches ADD COLUMN IF NOT EXISTS actor_model TEXT NOT NULL DEFAULT '';
ALTER TABLE awm_verification_batches ADD COLUMN IF NOT EXISTS actor_session TEXT NOT NULL DEFAULT '';

ALTER TABLE awm_review_attempts ADD COLUMN IF NOT EXISTS actor_harness TEXT NOT NULL DEFAULT '';
ALTER TABLE awm_review_attempts ADD COLUMN IF NOT EXISTS actor_model TEXT NOT NULL DEFAULT '';
ALTER TABLE awm_review_attempts ADD COLUMN IF NOT EXISTS actor_session TEXT NOT NULL DEFAULT '';
